# Generated by Django 4.2.1 on 2023-07-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_resigned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
