# Generated by Django 4.2.1 on 2023-07-11 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moc', models.CharField(default=None, max_length=10)),
                ('rate', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.IntegerField()),
                ('settled', models.BooleanField(blank=True, null=True)),
                ('final', models.BooleanField(blank=True, null=True)),
                ('promise', models.IntegerField()),
                ('date', models.DateField(max_length=20)),
                ('order_id', models.CharField(max_length=12)),
                ('invoice_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(default=None, max_length=200)),
                ('company', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('address', models.CharField(default=None, max_length=1000)),
                ('gstin', models.CharField(default=None, max_length=15)),
                ('phones', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('names', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('companys', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('emails', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('addresss', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('gstins', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('item_1', models.CharField(max_length=50)),
                ('desc_1', models.CharField(max_length=200)),
                ('qty_1', models.IntegerField(default=1)),
                ('rate_1', models.IntegerField(default=1)),
                ('item_2', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_2', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_2', models.IntegerField(blank=True, null=True)),
                ('rate_2', models.IntegerField(blank=True, null=True)),
                ('item_3', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_3', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_3', models.IntegerField(blank=True, null=True)),
                ('rate_3', models.IntegerField(blank=True, null=True)),
                ('item_4', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_4', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_4', models.IntegerField(blank=True, null=True)),
                ('rate_4', models.IntegerField(blank=True, null=True)),
                ('item_5', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_5', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_5', models.IntegerField(blank=True, null=True)),
                ('rate_5', models.IntegerField(blank=True, null=True)),
                ('item_6', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_6', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_6', models.IntegerField(blank=True, null=True)),
                ('rate_6', models.IntegerField(blank=True, null=True)),
                ('item_7', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_7', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_7', models.IntegerField(blank=True, null=True)),
                ('rate_7', models.IntegerField(blank=True, null=True)),
                ('item_8', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_8', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_8', models.IntegerField(blank=True, null=True)),
                ('rate_8', models.IntegerField(blank=True, null=True)),
                ('item_9', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_9', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_9', models.IntegerField(blank=True, null=True)),
                ('rate_9', models.IntegerField(blank=True, null=True)),
                ('item_10', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_10', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_10', models.IntegerField(blank=True, null=True)),
                ('rate_10', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField()),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa.referrer')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=1000)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.sale')),
            ],
        ),
    ]
