# Generated by Django 4.2.1 on 2023-07-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='promise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
