# Generated by Django 4.2.1 on 2023-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
