# Generated by Django 4.2.1 on 2023-07-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_sale_promise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.sale'),
        ),
    ]
