# Generated by Django 4.2.1 on 2023-08-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_alter_sale_final_alter_sale_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payments',
            field=models.BooleanField(default=False),
        ),
    ]
