# Generated by Django 4.2.1 on 2023-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_sale_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='grand_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
