# Generated by Django 4.2.1 on 2023-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_rename_final_sale_despatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
