# Generated by Django 4.2.1 on 2023-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_alter_client_email_alter_receipt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='addresss',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='companys',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='emails',
            field=models.EmailField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='grand_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gstins',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='names',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phones',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
